# Generated by Django 2.0.5 on 2018-05-16 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('cle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('data', models.IntegerField(default=0)),
                ('analyse', models.IntegerField(default=0)),
                ('dashboard', models.IntegerField(default=0)),
                ('connector', models.IntegerField(default=0)),
                ('model', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
